# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'myqtchatapp.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QComboBox, QFrame,
    QHBoxLayout, QLayout, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QSpacerItem, QTextEdit,
    QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(753, 640)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setBaseSize(QSize(600, 600))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(54, 54, 54, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(81, 81, 81, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(67, 67, 67, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(27, 27, 27, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(36, 36, 36, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush6 = QBrush(QColor(0, 0, 0, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        brush7 = QBrush(QColor(255, 255, 220, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        brush8 = QBrush(QColor(255, 255, 255, 127))
        brush8.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Active, QPalette.Accent, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        brush9 = QBrush(QColor(27, 27, 27, 127))
        brush9.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        brush10 = QBrush(QColor(38, 38, 38, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Accent, brush10)
        MainWindow.setPalette(palette)
        font = QFont()
        font.setPointSize(9)
        font.setKerning(False)
        font.setStyleStrategy(QFont.NoAntialias)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setAnimated(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setEnabled(True)
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy1)
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette1.setBrush(QPalette.Active, QPalette.Accent, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.Accent, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.Accent, brush10)
        self.centralwidget.setPalette(palette1)
        self.centralwidget.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.settings_menu_button = QPushButton(self.centralwidget)
        self.settings_menu_button.setObjectName(u"settings_menu_button")
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush11 = QBrush(QColor(0, 0, 127, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush11)
        brush12 = QBrush(QColor(0, 0, 190, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush12)
        brush13 = QBrush(QColor(0, 0, 158, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Midlight, brush13)
        brush14 = QBrush(QColor(0, 0, 63, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Dark, brush14)
        brush15 = QBrush(QColor(0, 0, 85, 255))
        brush15.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Mid, brush15)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette2.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette2.setBrush(QPalette.Active, QPalette.AlternateBase, brush14)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette2.setBrush(QPalette.Active, QPalette.Accent, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush11)
        palette2.setBrush(QPalette.Inactive, QPalette.Light, brush12)
        palette2.setBrush(QPalette.Inactive, QPalette.Midlight, brush13)
        palette2.setBrush(QPalette.Inactive, QPalette.Dark, brush14)
        palette2.setBrush(QPalette.Inactive, QPalette.Mid, brush15)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette2.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush14)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.Accent, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush11)
        palette2.setBrush(QPalette.Disabled, QPalette.Light, brush12)
        palette2.setBrush(QPalette.Disabled, QPalette.Midlight, brush13)
        palette2.setBrush(QPalette.Disabled, QPalette.Dark, brush14)
        palette2.setBrush(QPalette.Disabled, QPalette.Mid, brush15)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush14)
        palette2.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush14)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        palette2.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush11)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        brush16 = QBrush(QColor(0, 0, 63, 127))
        brush16.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush16)
#endif
        brush17 = QBrush(QColor(0, 0, 89, 255))
        brush17.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Disabled, QPalette.Accent, brush17)
        self.settings_menu_button.setPalette(palette2)
        font1 = QFont()
        font1.setFamilies([u"Arial"])
        font1.setPointSize(14)
        font1.setBold(False)
        font1.setItalic(False)
        font1.setKerning(True)
        font1.setStyleStrategy(QFont.NoAntialias)
        self.settings_menu_button.setFont(font1)
        self.settings_menu_button.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.settings_menu_button.setAcceptDrops(False)
        self.settings_menu_button.setAutoFillBackground(False)
        self.settings_menu_button.setAutoRepeatDelay(299)
        self.settings_menu_button.setAutoDefault(True)

        self.horizontalLayout.addWidget(self.settings_menu_button)

        self.horizontalSpacer = QSpacerItem(40, 40, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.clientbutton = QPushButton(self.centralwidget)
        self.clientbutton.setObjectName(u"clientbutton")
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush11)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush12)
        palette3.setBrush(QPalette.Active, QPalette.Midlight, brush13)
        palette3.setBrush(QPalette.Active, QPalette.Dark, brush14)
        palette3.setBrush(QPalette.Active, QPalette.Mid, brush15)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush)
        palette3.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette3.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette3.setBrush(QPalette.Active, QPalette.AlternateBase, brush14)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette3.setBrush(QPalette.Active, QPalette.Accent, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush11)
        palette3.setBrush(QPalette.Inactive, QPalette.Light, brush12)
        palette3.setBrush(QPalette.Inactive, QPalette.Midlight, brush13)
        palette3.setBrush(QPalette.Inactive, QPalette.Dark, brush14)
        palette3.setBrush(QPalette.Inactive, QPalette.Mid, brush15)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette3.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush14)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.Accent, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush11)
        palette3.setBrush(QPalette.Disabled, QPalette.Light, brush12)
        palette3.setBrush(QPalette.Disabled, QPalette.Midlight, brush13)
        palette3.setBrush(QPalette.Disabled, QPalette.Dark, brush14)
        palette3.setBrush(QPalette.Disabled, QPalette.Mid, brush15)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush14)
        palette3.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush14)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        palette3.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush11)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush16)
#endif
        palette3.setBrush(QPalette.Disabled, QPalette.Accent, brush17)
        self.clientbutton.setPalette(palette3)
        font2 = QFont()
        font2.setFamilies([u"Georgia"])
        font2.setPointSize(14)
        font2.setBold(False)
        font2.setKerning(False)
        font2.setStyleStrategy(QFont.NoAntialias)
        self.clientbutton.setFont(font2)
        self.clientbutton.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.clientbutton.setToolTipDuration(-2)
        self.clientbutton.setIconSize(QSize(16, 16))
        self.clientbutton.setAutoDefault(True)

        self.horizontalLayout.addWidget(self.clientbutton)

        self.horizontalSpacer_2 = QSpacerItem(40, 40, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_2)

        self.my_profile_box = QComboBox(self.centralwidget)
        self.my_profile_box.addItem("")
        self.my_profile_box.addItem("")
        self.my_profile_box.addItem("")
        self.my_profile_box.setObjectName(u"my_profile_box")
        self.my_profile_box.setEnabled(True)
        self.my_profile_box.setMinimumSize(QSize(3, 31))
        self.my_profile_box.setMaximumSize(QSize(16777215, 16777215))
        self.my_profile_box.setBaseSize(QSize(0, 7))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush11)
        palette4.setBrush(QPalette.Active, QPalette.Light, brush12)
        palette4.setBrush(QPalette.Active, QPalette.Midlight, brush13)
        palette4.setBrush(QPalette.Active, QPalette.Dark, brush14)
        palette4.setBrush(QPalette.Active, QPalette.Mid, brush15)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush)
        palette4.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush11)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette4.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette4.setBrush(QPalette.Active, QPalette.AlternateBase, brush14)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette4.setBrush(QPalette.Active, QPalette.Accent, brush6)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush11)
        palette4.setBrush(QPalette.Inactive, QPalette.Light, brush12)
        palette4.setBrush(QPalette.Inactive, QPalette.Midlight, brush13)
        palette4.setBrush(QPalette.Inactive, QPalette.Dark, brush14)
        palette4.setBrush(QPalette.Inactive, QPalette.Mid, brush15)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush11)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette4.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette4.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush14)
        palette4.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette4.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette4.setBrush(QPalette.Inactive, QPalette.Accent, brush6)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush14)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush11)
        palette4.setBrush(QPalette.Disabled, QPalette.Light, brush12)
        palette4.setBrush(QPalette.Disabled, QPalette.Midlight, brush13)
        palette4.setBrush(QPalette.Disabled, QPalette.Dark, brush14)
        palette4.setBrush(QPalette.Disabled, QPalette.Mid, brush15)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush14)
        palette4.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush14)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        palette4.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette4.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush11)
        palette4.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette4.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush16)
#endif
        palette4.setBrush(QPalette.Disabled, QPalette.Accent, brush17)
        self.my_profile_box.setPalette(palette4)
        font3 = QFont()
        font3.setFamilies([u"Arial"])
        font3.setPointSize(14)
        font3.setBold(False)
        font3.setKerning(False)
        font3.setStyleStrategy(QFont.NoAntialias)
        self.my_profile_box.setFont(font3)
        self.my_profile_box.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.my_profile_box.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.my_profile_box.setToolTipDuration(0)
        self.my_profile_box.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.my_profile_box.setAutoFillBackground(False)
        self.my_profile_box.setEditable(True)
        self.my_profile_box.setMaxVisibleItems(10)
        self.my_profile_box.setInsertPolicy(QComboBox.InsertPolicy.InsertAtBottom)
        self.my_profile_box.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.my_profile_box.setMinimumContentsLength(0)
        self.my_profile_box.setDuplicatesEnabled(False)
        self.my_profile_box.setFrame(False)

        self.horizontalLayout.addWidget(self.my_profile_box)


        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setEnabled(False)
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        brush18 = QBrush(QColor(170, 255, 255, 255))
        brush18.setStyle(Qt.SolidPattern)
        palette5.setBrush(QPalette.Active, QPalette.Button, brush18)
        palette5.setBrush(QPalette.Active, QPalette.Light, brush)
        brush19 = QBrush(QColor(212, 255, 255, 255))
        brush19.setStyle(Qt.SolidPattern)
        palette5.setBrush(QPalette.Active, QPalette.Midlight, brush19)
        brush20 = QBrush(QColor(85, 127, 127, 255))
        brush20.setStyle(Qt.SolidPattern)
        palette5.setBrush(QPalette.Active, QPalette.Dark, brush20)
        brush21 = QBrush(QColor(113, 170, 170, 255))
        brush21.setStyle(Qt.SolidPattern)
        palette5.setBrush(QPalette.Active, QPalette.Mid, brush21)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush6)
        palette5.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush6)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush18)
        palette5.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette5.setBrush(QPalette.Active, QPalette.AlternateBase, brush19)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        brush22 = QBrush(QColor(0, 0, 0, 127))
        brush22.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Active, QPalette.PlaceholderText, brush22)
#endif
        palette5.setBrush(QPalette.Active, QPalette.Accent, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush18)
        palette5.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Midlight, brush19)
        palette5.setBrush(QPalette.Inactive, QPalette.Dark, brush20)
        palette5.setBrush(QPalette.Inactive, QPalette.Mid, brush21)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.ButtonText, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush18)
        palette5.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush19)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush22)
#endif
        palette5.setBrush(QPalette.Inactive, QPalette.Accent, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush20)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush18)
        palette5.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.Midlight, brush19)
        palette5.setBrush(QPalette.Disabled, QPalette.Dark, brush20)
        palette5.setBrush(QPalette.Disabled, QPalette.Mid, brush21)
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush20)
        palette5.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.ButtonText, brush20)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush18)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush18)
        palette5.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette5.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush18)
        palette5.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette5.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        brush23 = QBrush(QColor(85, 127, 127, 127))
        brush23.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush23)
#endif
        brush24 = QBrush(QColor(246, 255, 255, 255))
        brush24.setStyle(Qt.SolidPattern)
        palette5.setBrush(QPalette.Disabled, QPalette.Accent, brush24)
        self.frame.setPalette(palette5)
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)

        self.verticalLayout_2.addWidget(self.frame)

        self.msg_history = QTextEdit(self.centralwidget)
        self.msg_history.setObjectName(u"msg_history")
        self.msg_history.setEnabled(True)
        self.msg_history.setMinimumSize(QSize(13, 13))
        self.msg_history.setBaseSize(QSize(12, 0))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        brush25 = QBrush(QColor(255, 240, 157, 255))
        brush25.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Button, brush25)
        palette6.setBrush(QPalette.Active, QPalette.Light, brush)
        brush26 = QBrush(QColor(255, 247, 206, 255))
        brush26.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Midlight, brush26)
        brush27 = QBrush(QColor(127, 120, 78, 255))
        brush27.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Dark, brush27)
        brush28 = QBrush(QColor(170, 160, 105, 255))
        brush28.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Mid, brush28)
        palette6.setBrush(QPalette.Active, QPalette.Text, brush6)
        palette6.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush6)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush25)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush25)
        palette6.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette6.setBrush(QPalette.Active, QPalette.AlternateBase, brush26)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Active, QPalette.PlaceholderText, brush22)
#endif
        palette6.setBrush(QPalette.Active, QPalette.Accent, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush25)
        palette6.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Midlight, brush26)
        palette6.setBrush(QPalette.Inactive, QPalette.Dark, brush27)
        palette6.setBrush(QPalette.Inactive, QPalette.Mid, brush28)
        palette6.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette6.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.ButtonText, brush6)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush25)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush25)
        palette6.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette6.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush26)
        palette6.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette6.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush22)
#endif
        palette6.setBrush(QPalette.Inactive, QPalette.Accent, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush27)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush25)
        palette6.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.Midlight, brush26)
        palette6.setBrush(QPalette.Disabled, QPalette.Dark, brush27)
        palette6.setBrush(QPalette.Disabled, QPalette.Mid, brush28)
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush27)
        palette6.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.ButtonText, brush27)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush25)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush25)
        palette6.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush25)
        palette6.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette6.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        brush29 = QBrush(QColor(127, 120, 78, 127))
        brush29.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush29)
#endif
        brush30 = QBrush(QColor(255, 252, 233, 255))
        brush30.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Disabled, QPalette.Accent, brush30)
        self.msg_history.setPalette(palette6)
        font4 = QFont()
        font4.setFamilies([u"Stylus BT"])
        font4.setPointSize(24)
        font4.setUnderline(False)
        font4.setKerning(False)
        font4.setStyleStrategy(QFont.NoAntialias)
        self.msg_history.setFont(font4)
        self.msg_history.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.msg_history.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.msg_history.setReadOnly(True)

        self.verticalLayout_2.addWidget(self.msg_history)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setSpacing(9)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(0, 11, 0, 11)
        self.msg_bar = QLineEdit(self.centralwidget)
        self.msg_bar.setObjectName(u"msg_bar")
        self.msg_bar.setEnabled(True)
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy2.setHorizontalStretch(10)
        sizePolicy2.setVerticalStretch(10)
        sizePolicy2.setHeightForWidth(self.msg_bar.sizePolicy().hasHeightForWidth())
        self.msg_bar.setSizePolicy(sizePolicy2)
        self.msg_bar.setMinimumSize(QSize(0, 0))
        self.msg_bar.setSizeIncrement(QSize(10, 0))
        self.msg_bar.setBaseSize(QSize(700, 50))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette7.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette7.setBrush(QPalette.Active, QPalette.Dark, brush1)
        palette7.setBrush(QPalette.Active, QPalette.Mid, brush1)
        palette7.setBrush(QPalette.Active, QPalette.Text, brush)
        palette7.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette7.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette7.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette7.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette7.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette7.setBrush(QPalette.Active, QPalette.AlternateBase, brush1)
        palette7.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette7.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette7.setBrush(QPalette.Active, QPalette.Accent, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette7.setBrush(QPalette.Inactive, QPalette.Dark, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Mid, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette7.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette7.setBrush(QPalette.Inactive, QPalette.Accent, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette7.setBrush(QPalette.Disabled, QPalette.Dark, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Mid, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Text, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.ButtonText, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette7.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        palette7.setBrush(QPalette.Disabled, QPalette.Accent, brush1)
        self.msg_bar.setPalette(palette7)
        font5 = QFont()
        font5.setPointSize(21)
        font5.setBold(True)
        font5.setItalic(False)
        font5.setKerning(False)
        font5.setStyleStrategy(QFont.NoAntialias)
        self.msg_bar.setFont(font5)
        self.msg_bar.setCursor(QCursor(Qt.CursorShape.IBeamCursor))
        self.msg_bar.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.msg_bar.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.msg_bar.setToolTipDuration(0)
        self.msg_bar.setAutoFillBackground(False)
        self.msg_bar.setInputMask(u"")
        self.msg_bar.setMaxLength(32780)
        self.msg_bar.setFrame(True)
        self.msg_bar.setCursorPosition(0)
        self.msg_bar.setAlignment(Qt.AlignmentFlag.AlignJustify|Qt.AlignmentFlag.AlignVCenter)
        self.msg_bar.setDragEnabled(False)
        self.msg_bar.setReadOnly(False)
        self.msg_bar.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.msg_bar.setClearButtonEnabled(True)

        self.horizontalLayout_3.addWidget(self.msg_bar)

        self.sent_button = QPushButton(self.centralwidget)
        self.sent_button.setObjectName(u"sent_button")
        self.sent_button.setEnabled(True)
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.sent_button.sizePolicy().hasHeightForWidth())
        self.sent_button.setSizePolicy(sizePolicy3)
        self.sent_button.setMaximumSize(QSize(16777215, 16777213))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        brush31 = QBrush(QColor(9, 51, 200, 255))
        brush31.setStyle(Qt.SolidPattern)
        palette8.setBrush(QPalette.Active, QPalette.Button, brush31)
        brush32 = QBrush(QColor(56, 100, 255, 255))
        brush32.setStyle(Qt.SolidPattern)
        palette8.setBrush(QPalette.Active, QPalette.Light, brush32)
        brush33 = QBrush(QColor(32, 75, 227, 255))
        brush33.setStyle(Qt.SolidPattern)
        palette8.setBrush(QPalette.Active, QPalette.Midlight, brush33)
        brush34 = QBrush(QColor(4, 25, 100, 255))
        brush34.setStyle(Qt.SolidPattern)
        palette8.setBrush(QPalette.Active, QPalette.Dark, brush34)
        brush35 = QBrush(QColor(6, 34, 133, 255))
        brush35.setStyle(Qt.SolidPattern)
        palette8.setBrush(QPalette.Active, QPalette.Mid, brush35)
        palette8.setBrush(QPalette.Active, QPalette.Text, brush6)
        palette8.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette8.setBrush(QPalette.Active, QPalette.ButtonText, brush6)
        palette8.setBrush(QPalette.Active, QPalette.Base, brush)
        palette8.setBrush(QPalette.Active, QPalette.Window, brush31)
        palette8.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        brush36 = QBrush(QColor(132, 153, 227, 255))
        brush36.setStyle(Qt.SolidPattern)
        palette8.setBrush(QPalette.Active, QPalette.AlternateBase, brush36)
        palette8.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette8.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Active, QPalette.PlaceholderText, brush22)
#endif
        palette8.setBrush(QPalette.Active, QPalette.Accent, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush31)
        palette8.setBrush(QPalette.Inactive, QPalette.Light, brush32)
        palette8.setBrush(QPalette.Inactive, QPalette.Midlight, brush33)
        palette8.setBrush(QPalette.Inactive, QPalette.Dark, brush34)
        palette8.setBrush(QPalette.Inactive, QPalette.Mid, brush35)
        palette8.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette8.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.ButtonText, brush6)
        palette8.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Window, brush31)
        palette8.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette8.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush36)
        palette8.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette8.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush22)
#endif
        palette8.setBrush(QPalette.Inactive, QPalette.Accent, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush34)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush31)
        palette8.setBrush(QPalette.Disabled, QPalette.Light, brush32)
        palette8.setBrush(QPalette.Disabled, QPalette.Midlight, brush33)
        palette8.setBrush(QPalette.Disabled, QPalette.Dark, brush34)
        palette8.setBrush(QPalette.Disabled, QPalette.Mid, brush35)
        palette8.setBrush(QPalette.Disabled, QPalette.Text, brush34)
        palette8.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.ButtonText, brush34)
        palette8.setBrush(QPalette.Disabled, QPalette.Base, brush31)
        palette8.setBrush(QPalette.Disabled, QPalette.Window, brush31)
        palette8.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette8.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush31)
        palette8.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette8.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        brush37 = QBrush(QColor(4, 25, 100, 127))
        brush37.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush37)
#endif
        brush38 = QBrush(QColor(16, 69, 255, 255))
        brush38.setStyle(Qt.SolidPattern)
        palette8.setBrush(QPalette.Disabled, QPalette.Accent, brush38)
        self.sent_button.setPalette(palette8)
        self.sent_button.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        icon = QIcon()
        icon.addFile(u"senticon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.sent_button.setIcon(icon)
        self.sent_button.setIconSize(QSize(35, 34))
        self.sent_button.setAutoDefault(False)
        self.sent_button.setFlat(False)

        self.horizontalLayout_3.addWidget(self.sent_button)


        self.verticalLayout_2.addLayout(self.horizontalLayout_3)


        self.verticalLayout_3.addLayout(self.verticalLayout_2)


        self.verticalLayout.addLayout(self.verticalLayout_3)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.settings_menu_button.setDefault(False)
        self.my_profile_box.setCurrentIndex(0)
        self.sent_button.setDefault(True)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.settings_menu_button.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
#if QT_CONFIG(shortcut)
        self.settings_menu_button.setShortcut("")
#endif // QT_CONFIG(shortcut)
        self.clientbutton.setText(QCoreApplication.translate("MainWindow", u"Client/Server", None))
        self.my_profile_box.setItemText(0, QCoreApplication.translate("MainWindow", u"               My Profile", None))
        self.my_profile_box.setItemText(1, QCoreApplication.translate("MainWindow", u"               Account Settings", None))
        self.my_profile_box.setItemText(2, QCoreApplication.translate("MainWindow", u"               Log Out", None))

#if QT_CONFIG(tooltip)
        self.my_profile_box.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.my_profile_box.setCurrentText(QCoreApplication.translate("MainWindow", u"               My Profile", u"Profile"))
        self.my_profile_box.setPlaceholderText("")
        self.msg_history.setMarkdown("")
        self.msg_history.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Stylus BT'; font-size:24pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'Segoe UI'; font-size:9pt;\"><br /></p>\n"
"<hr /></body></html>", None))
        self.msg_bar.setText("")
        self.msg_bar.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Type", None))
        self.sent_button.setText("")
#if QT_CONFIG(shortcut)
        self.sent_button.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
    # retranslateUi

